experiment_id: B1_VGG16
group: B
model: vgg16
train_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/B/B1/01-train/
val_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/B/B1/02-validation/
test_set_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/B/B1/03-test/
num_classes: 2
class_names:
- crack
- undamaged
class_weights:
- 1.0
- 1.0
epochs: 5
batch_size: 32
learning_rate: 0.00001
weight_decay: 0.0001
random_seed: 42
