experiment_id: C_efflorescence_RESNET50
group: C
model: resnet50
train_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/C/C1/01-train/
val_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/C/C1/02-validation/
test_set_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/C/C1/03-test/
num_classes: 4
class_names:
- crack
- efflorescence
- spalling
- undamaged
class_weights:
- 1.0
- 3.0
- 1.0
- 1.0
epochs: 25
batch_size: 32
learning_rate: 0.00001
weight_decay: 0.000
random_seed: 42
