experiment_id: C_spalling_RESNET50
group: C
model: resnet50
train_path: C:/Users/jcac/Documents/03-TRABAJO/11-PhD/Dataset/A1/01-train/
val_path: C:/Users/jcac/Documents/03-TRABAJO/11-PhD/Dataset/A1/02-validation/
test_set_path: C:/Users/jcac/Documents/03-TRABAJO/11-PhD/Dataset/A1/03-test/
num_classes: 4
class_names:
- crack
- efflorescence
- spalling
- undamaged
class_weights:
- 1.0
- 1.0
- 3.0
- 1.0
epochs: 20
batch_size: 32
learning_rate: 0.0001
random_seed: 42
