experiment_id: A4_RESNET50
group: A
model: resnet50
train_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/A/A4/01-train/
val_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/A/A4/02-validation/
test_set_path: D:/JCA/07-Data/01_Concrete/03-experiment_datasets/Test/
num_classes: 4
class_names:
- crack
- efflorescence
- spalling
- undamaged
class_weights:
- 1.0
- 1.0
- 1.0
- 1.0
epochs: 70
batch_size: 32
learning_rate: 0.0001
random_seed: 42
